---
resources:
- name: git-resource
  type: git
  source:
    uri: git@github.com:m-kratochvil/ansible-ci.git
    branch: main
    private_key: {{ccloud-net-ssh-key}}

jobs:
- name: run-playbook
  plan:
  - get: git-resource
  - task: task01
    config: 
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: mkratochvil/ansirun
      inputs:
      - name: git-resource
        path: ./ansible-ci
      run:
          path: sh
          args:
          - -exc
          - |
            cd ansible-ci/ansible
            ansible --version
            ansible localhost -m ping
