---
- name: Show cluster HA state.
  hosts: 'device_roles_loadbalancer,&{{ targets }}'
  gather_facts: false
  collections:
    - f5networks.f5_modules
    - ansible.netcommon
  vars_files:
    - ../vars/vault.yaml
    - ../vars/groupvars_global.yaml
    - ../vars/groupvars_{{ region }}.yaml
    - ../vars/hostvars_{{ region }}.yaml
  
  tasks:

    - name: Gather BIG-IP facts.
      bigip_device_info:
        gather_subset: "devices"
        provider: "{{ provider }}"
      delegate_to: localhost
      check_mode: no
      register: var_gathered

    - name: Show the target device HA state.
      debug:
        msg: "Device {{ inventory_hostname }} current state is \
          {{ var_gathered.devices | json_query(\"[?self=='yes'].failover_state\") | first | upper }}"
