---
- name: Show cluster HA state.
  hosts: qa-de-1a-f511
  gather_facts: false
  collections:
    - f5networks.f5_modules
    - ansible.netcommon
  vars_files:
    - vars/vault.yaml
    - vars/global.yaml
  
  tasks:

    - name: Gather BIG-IP facts.
      bigip_device_info:
        gather_subset: "devices"
        provider: "{{ provider }}"
      delegate_to: localhost
      check_mode: no
      register: var_gathered

    - name: Show the target device HA state.
      debug:
        msg: "Device {{ inventory_hostname }} current state is \
          {{ var_gathered.devices | json_query(\"[?self=='yes'].failover_state\") | first | upper }}"
